export const GET_POKEMON_LIST = 'GET_POKEMON_LIST';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const SEARCH_POKEMON_DETAIL = 'SEARCH_POKEMON_DETAIL';
export const RESET_POKEMON_DETAIL = 'RESET_POKEMON_DETAIL';